cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$' , views.cart_detail , name = 'cart_detail'),
	re_path(r'^add/(?P<pk>\d+)/$' , views.cart_add , name = 'cart_add'),
	re_path(r'^remove/(?P<pk>\d+)/$' , views.cart_remove , name = 'cart_remove'),

] 

first/urls.py
from django.urls import re_path
from django.views.generic import ListView, DetailView

from . import views
from . import models

app_name = 'first'


urlpatterns = [
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^about-us/$', views.about, name = 'about-us'),
    re_path(r'^shop/categories/laptops/$', ListView.as_view(queryset = models.Laptop.objects.all(), template_name = "first/laptop-card.html")),
    re_path(r'^shop/categories/laptops/(?P<pk>\d+)/$', DetailView.as_view(model = models.Laptop, template_name = "first/laptop.html")),
    re_path(r'^shop/categories/mobiles/$', ListView.as_view(queryset = models.Mobile.objects.all(), template_name = "first/mobile-card.html"),name = 'list'),
    #re_path(r'^shop/categories/mobiles/(?P<pk>\d+)/$', DetailView.as_view(model = models.Mobile, template_name = "first/mobile.html")),
    re_path(r'^shop/categories/tablets/$', ListView.as_view(queryset = models.Tablet.objects.all(), template_name = "first/tablet-card.html")),
    re_path(r'^shop/categories/tablets/(?P<pk>\d+)/$', DetailView.as_view(model = models.Tablet, template_name = "first/tablet.html")),
    re_path(r'^shop/categories/headsets/$', ListView.as_view(queryset = models.Headset.objects.all(), template_name = "first/headset-card.html")),
    re_path(r'^shop/categories/headsets/(?P<pk>\d+)/$', DetailView.as_view(model = models.Headset, template_name = "first/headset.html")),
    re_path(r'^shop/categories/powerbanks/$', ListView.as_view(queryset = models.PowerBank.objects.all(), template_name = "first/powerbank-card.html")),
    re_path(r'^shop/categories/powerbanks/(?P<pk>\d+)/$', DetailView.as_view(model = models.PowerBank, template_name = "first/powerbank.html")),
    re_path(r'^shop/categories/memorycards/$', ListView.as_view(queryset = models.MemoryCard.objects.all(), template_name = "first/memorycard-card.html")),
    re_path(r'^shop/categories/memorycards/(?P<pk>\d+)/$', DetailView.as_view(model = models.MemoryCard, template_name = "first/memorycard.html")),
    re_path(r'^shop/categories/chargers/$', ListView.as_view(queryset = models.Charger.objects.all(), template_name = "first/charger-card.html")),
    re_path(r'^shop/categories/chargers/(?P<pk>\d+)/$', DetailView.as_view(model = models.Charger, template_name = "first/charger.html")),
    re_path(r'^shop/categories/$', views.category, name = 'category'),
    re_path(r'^shop/categories/mobiles/(?P<pk>\d+)/$' , views.product_detail , name = 'detail'),
]

summer2/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static

from summer2 import settings


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('first.urls' , namespace = 'first')),
    re_path(r'^cart/',include('cart.urls' , namespace='cart')),
    re_path(r'^login/', include('sign.urls')),
    re_path(r'^search/', include('search.urls', namespace = 'search')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):

	quantity_choices = [(i, str(i)) for i in range(1, 11)]
	quantity = forms.TypedChoiceField(label = "Quantity ", choices = quantity_choices , coerce = int )
	update = forms.BooleanField(required = False , initial = False , widget = forms.HiddenInput)

cart/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views.decorators.http import require_POST
from first.models import Mobile
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request , pk):
	cart = Cart(request)
	mobile = get_object_or_404(Mobile , pk = pk)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(mobile = mobile , quantity = cd['quantity'] , update_quantity = cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request , pk):
	cart = Cart(request)
	mobile = get_object_or_404(Mobile , pk = pk)
	cart.remove(mobile)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial = { 'quantity' : item['quantity'] , 'update' : True})
	context = {'cart' : cart}
	return render(request , 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends 'first/base.html' %}
	{% load static %}

	{% block title %}<title>Shopping Cart</title>{% endblock %}

	{% block content %}
		<div class = "text-right pr-3 pr-md-3 pd-lg-3">
  			{% with total_items=cart|length %}
    			{% if cart|length > 0 %}
      				<h2>Your cart: </h2>
      				<a href="{% url 'cart:cart_detail' %}">
        			<h2>{{ total_items }} item{{ total_items|pluralize }},
        			&#x20B9;{{ cart.get_total_price }}</h2>
      				</a>
    			{% else %}
     				 <h2>Your cart is empty</h2>
    			{% endif %}
  			{% endwith %}			
		</div>
		<h1>Your Shopping Cart</h1>
		<table class = "table table-striped" style = "font-size: 20px">
			<thead>
				<tr>
					<td>Image</td>
					<td>Product</td>
					<td>Quantity</td>
					<td>Remove</td>
					<td>Unit Price</td>
					<td>Price</td>
				</tr>
			</thead>
			<tbody>
				{% for item in cart %}
					{% with mobile=item.mobile %}
						<tr>
							<td><img src = "{{ mobile.Image.url }}" height="50%"></td>
							<td>{{ mobile.Manufacturer }} {{ mobile.Model_Name }}</td>
							<td>{{ item.quantity }}</td>
							<td><a href = "{% url 'cart:cart_remove' mobile.id %}">Remove</a></td>
							<td >&#x20B9;{{ item.price }}</td>
							<td>&#x20B9;{{ item.total_price }}</td>
						</tr>
					{% endwith %}
				{% endfor %}
				<tr class = "total">
					<td>Total</td>
					<td colspan = "4"></td>
					<td class = "num">&#x20B9;{{ cart.get_total_price }}</td>
				</tr>
			</tbody>						
		</table>
		<p class = "text-right">
			<a href = "{% url 'first:category' %}" class = "button light btn-lg">Continue Shopping</a>
			<a href = "#" class = "button btn-lg">Checkout</a>
		</p>
	{% endblock %}