cart/urls.py
from django.urls import re_path
from . import views

app_name = 'cart'

urlpatterns = [
	re_path(r'^$' , views.cart_detail , name = 'cart_detail'),
	re_path(r'^add/(?P<pk>\d+)/$' , views.cart_add , name = 'cart_add'),
	re_path(r'^remove/(?P<pk>\d+)/$' , views.cart_remove , name = 'cart_remove'),

] 

first/urls.py
from django.urls import re_path
from django.views.generic import ListView, DetailView

from . import views
from . import models

app_name = 'first'


urlpatterns = [
    re_path(r'^$', views.index, name = 'index'),
    re_path(r'^about-us/$', views.about, name = 'about-us'),
    re_path(r'^shop/categories/laptops/$', ListView.as_view(queryset = models.Laptop.objects.all(), template_name = "first/laptop-card.html")),
    re_path(r'^shop/categories/laptops/(?P<pk>\d+)/$', DetailView.as_view(model = models.Laptop, template_name = "first/laptop.html")),
    re_path(r'^shop/categories/mobiles/$', ListView.as_view(queryset = models.Mobile.objects.all(), template_name = "first/mobile-card.html"),name = 'list'),
    #re_path(r'^shop/categories/mobiles/(?P<pk>\d+)/$', DetailView.as_view(model = models.Mobile, template_name = "first/mobile.html")),
    re_path(r'^shop/categories/tablets/$', ListView.as_view(queryset = models.Tablet.objects.all(), template_name = "first/tablet-card.html")),
    re_path(r'^shop/categories/tablets/(?P<pk>\d+)/$', DetailView.as_view(model = models.Tablet, template_name = "first/tablet.html")),
    re_path(r'^shop/categories/headsets/$', ListView.as_view(queryset = models.Headset.objects.all(), template_name = "first/headset-card.html")),
    re_path(r'^shop/categories/headsets/(?P<pk>\d+)/$', DetailView.as_view(model = models.Headset, template_name = "first/headset.html")),
    re_path(r'^shop/categories/powerbanks/$', ListView.as_view(queryset = models.PowerBank.objects.all(), template_name = "first/powerbank-card.html")),
    re_path(r'^shop/categories/powerbanks/(?P<pk>\d+)/$', DetailView.as_view(model = models.PowerBank, template_name = "first/powerbank.html")),
    re_path(r'^shop/categories/memorycards/$', ListView.as_view(queryset = models.MemoryCard.objects.all(), template_name = "first/memorycard-card.html")),
    re_path(r'^shop/categories/memorycards/(?P<pk>\d+)/$', DetailView.as_view(model = models.MemoryCard, template_name = "first/memorycard.html")),
    re_path(r'^shop/categories/chargers/$', ListView.as_view(queryset = models.Charger.objects.all(), template_name = "first/charger-card.html")),
    re_path(r'^shop/categories/chargers/(?P<pk>\d+)/$', DetailView.as_view(model = models.Charger, template_name = "first/charger.html")),
    re_path(r'^shop/categories/$', views.category, name = 'category'),
    re_path(r'^shop/categories/mobiles/(?P<pk>\d+)/$' , views.product_detail , name = 'detail'),
]

search/urls.py
from django.urls import re_path
from . import views

app_name = 'search'

urlpatterns = [
	re_path(r'^$' , views.search_result , name = 'search_result')
]

summer2/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static

from summer2 import settings


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('first.urls' , namespace = 'first')),
    re_path(r'^cart/',include('cart.urls' , namespace='cart')),
    re_path(r'^login/', include('sign.urls')),
    re_path(r'^search/', include('search.urls', namespace = 'search')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

first/models.py
from django.db import models
from django.urls import reverse

class Mobile(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #image
    Image = models.ImageField(default = None)

    #Specifications
    Display_Size = models.FloatField()
    CPU = models.CharField(max_length = 100)
    RAM = models.DecimalField(max_digits = 3, decimal_places = 0)
    GPU = models.CharField(max_length = 100)
    Front_Camera = models.DecimalField(max_digits = 3, decimal_places = 1)
    Rear_Camera = models.DecimalField(max_digits = 3, decimal_places = 1)
    Weight = models.DecimalField(max_digits = 6, decimal_places = 2)
    Resolution = models.CharField(max_length = 40)
    Battery_Rating = models.DecimalField(max_digits = 5, decimal_places = 0)
    Colour = models.CharField(max_length = 50)
    OS = models.CharField(max_length = 40)
    Storage = models.CharField(max_length = 40)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'Mobile: {} {}'.format(self.Manufacturer, self.Model_Name)

    def get_absolute_url(self):
        return reverse('first:detail' , args = [self.id])


class Laptop(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #image
    Image = models.ImageField(default = None)

    #Specifications
    Screen_Size = models.FloatField()
    CPU = models.CharField(max_length = 100)
    RAM = models.DecimalField(max_digits = 3, decimal_places = 0)
    GPU = models.CharField(max_length = 100)
    Camera = models.CharField(max_length = 40)
    IO = models.TextField(max_length = 480)
    Storage = models.CharField(max_length = 100)
    OS = models.CharField(max_length = 40)
    Battery_Rating = models.DecimalField(max_digits = 5, decimal_places = 0)
    RAM_Type = models.CharField(max_length = 30)
    VRAM = models.DecimalField(max_digits = 3, decimal_places = 1)
    Internet_Connectivity = models.TextField(max_length = 140)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'Laptop: {} {}'.format(self.Manufacturer, self.Model_Name)

class Tablet(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #image
    Image = models.ImageField(default = None)

    #Specifications
    Display_Size = models.FloatField()
    CPU = models.CharField(max_length = 100)
    RAM = models.DecimalField(max_digits = 3, decimal_places = 0)
    GPU = models.CharField(max_length = 100)
    Front_Camera = models.DecimalField(max_digits = 3, decimal_places = 1)
    Rear_Camera = models.DecimalField(max_digits = 3, decimal_places = 1)
    Weight = models.DecimalField(max_digits = 6, decimal_places = 2)
    Resolution = models.CharField(max_length = 40)
    Battery_Rating = models.DecimalField(max_digits = 5, decimal_places = 0)
    Colour = models.CharField(max_length = 50)
    SKU = models.CharField(max_length = 40)
    OS = models.CharField(max_length = 40)
    Storage = models.CharField(max_length = 40)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)


    def __str__(self):
        return 'Tablet: {} {}'.format(self.Manufacturer, self.Model_Name)

class Headset(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #Image
    Image = models.ImageField(default = None)

    #Specifications
    Colour = models.CharField(max_length = 50)
    Driver_Size = models.DecimalField(max_digits = 4, decimal_places = 0)
    Type = models.CharField(max_length = 90)
    Driver_Type = models.CharField(max_length = 100)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'Headset: {} {}'.format(self.Manufacturer, self.Model_Name)

class PowerBank(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #Image
    Image = models.ImageField(default = None)

    #Specifications
    Capacity = models.CharField(max_length = 50)
    Input_Power = models.CharField(max_length = 50)
    Output_Power = models.CharField(max_length = 50)
    Output_ports = models.DecimalField(max_digits = 2, decimal_places = 0)
    Weight = models.DecimalField(max_digits = 6, decimal_places = 2)
    Dimension = models.CharField(max_length = 60)
    Colour = models.CharField(max_length = 50)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'PowerBank: {} {}'.format(self.Manufacturer, self.Model_Name)

class MemoryCard(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #Image
    Image = models.ImageField(default = None)

    #Specifications
    Capacity = models.DecimalField(max_digits = 3, decimal_places = 0)
    Write_Speed = models.DecimalField(max_digits = 3, decimal_places = 0)
    Dimension = models.CharField(max_length = 60)
    Weight = models.DecimalField(max_digits = 6, decimal_places = 2)
    Colour = models.CharField(max_length = 50)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'MemoryCard: {} {}'.format(self.Manufacturer, self.Model_Name)
        

class Charger(models.Model):
    Manufacturer = models.CharField(max_length = 60)
    Model_Name = models.CharField(max_length = 100)
    Model_Number = models.CharField(max_length = 50)

    #Image
    Image = models.ImageField(default = None)

    #PowerFeatures
    Power_Input = models.CharField(max_length = 60)
    Power_Output = models.DecimalField(max_digits = 3 , decimal_places = 0)

    #Specification
    Cable_Length = models.DecimalField(max_digits = 6 , decimal_places = 2)
    Cable_Type = models.CharField(max_length = 50)

    #Warranty
    Warranty_Type = models.CharField(max_length = 50)
    Warranty_Duration = models.CharField(max_length = 70)

    Description = models.TextField(max_length = 1000)
    Price = models.DecimalField(max_digits = 7, decimal_places = 2)

    def __str__(self):
        return 'Charger: {} {}'.format(self.Manufacturer, self.Model_Name)










        

first/views.py
from django.shortcuts import render,get_object_or_404
from cart.forms import CartAddProductForm
from . import models
from first.models import Mobile

def index(request):
    mobile = models.Mobile.objects.all()
    laptop = models.Laptop.objects.all()
    tablet = models.Tablet.objects.all()
    headset = models.Headset.objects.all()
    memorycard = models.MemoryCard.objects.all()
    powerbank = models.PowerBank.objects.all()
    charger = models.Charger.objects.all()


    args = {
        'mobile': mobile,
        'laptop': laptop,
        'tablet': tablet,
        'headset': headset,
        'memorycard': memorycard,
        'powerbank': powerbank,
        'charger': charger
    }

    return render(request, 'first/index.html', args)

def about(request):
    return render(request, 'first/about-us.html')

def product(request):
    return render(request, 'first/product-page.html')

def category(request):
    return render(request, 'first/product-category.html')

def product_detail(request , pk):
    mobile = get_object_or_404(Mobile , pk = pk)
    cart_product_form = CartAddProductForm()
    context = {'mobile' : mobile , 'cart_product_form' : cart_product_form}
    return render(request ,'first/mobile.html' , context)

first/templates/first/about-us.html
{% extends 'first/base.html' %}
    {% block nav-about %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'first:about-us' %}">About Us</a>
        </li>
    {% endblock %}

    {% block content %}
        <h1>HI! THERE'S NOTHING HERE!</h1>   
    {% endblock %}

first/templates/first/base.html
<!DOCTYPE html>
<html lang="en" >

<head>
    {% load static %}

    <meta charset="UTF-8">
    {% block title %}<title>Online store</title>{% endblock %}
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/1.7.22/css/materialdesignicons.min.css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'first/css/style.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-xl-4">
        <a class="navbar-brand" href="{% url 'first:index' %}">
            <img src = "{% static 'first/img/logo.png' %}" width = "50" height = "30" alt = "logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                {% block nav-home %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                {% endblock %}

                {% block nav-shop %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:category' %}">Shop</a>
                    </li>
                {% endblock %}

                {% block nav-about %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'first:about-us' %}">About Us</a>
                    </li>
                {% endblock %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Contact
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">support@legitweb.com</a>
                        <a class="dropdown-item" href="#">Call: 1-800-SCAMMED</a>
                    </div>
                </li>
            </ul>

            <form class = "form-inline my-2 my-lg-0" action="{% url 'search:search_result' %}" method = "get">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label = "Search" name="q">
                <button class="btn btn-primary my-2 my-sm-0" type = "submit"><i class ="fas fa-search"></i></button>
            </form>

            <div class = "navbar-nav nav-item text-inline">
                {% block nav-login %}
                    {% if user.is_authenticated %}
                        <a class = "nav-link" href = "{% url 'logout' %}">Logout</a>

                    {% else %}
                        <a class = "nav-link" href = "/login/">Login</a>
                    {% endif %}
                {% endblock %}
                {% block nav-cart %}
                    {% if user.is_authenticated %}       
                      <a class = "nav-link" href = "{% url 'cart:cart_detail' %}">Cart</a>     
                    {% else %}        
                       <a class = "nav-link disabled" style = "cursor: not-allowed;" data-toggle = "tooltip" data-placement = "left" title = "Sign in to use the cart">Cart</a>      
                    {% endif %}       
                {% endblock %}
            </div>
        </div>
    </nav>

    {% block front_page %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script type="text/javascript">      
        $(document).ready(function()      
        {     
            $('[data-toggle = "tooltip"]').tooltip();     
        });       
    </script>
</body>

</html>

first/templates/first/charger-card.html
{% extends 'first/product-card.html' %}

{% block price %}
    <p class = "card-text text-success">&#x20B9; {{ product.Price }}</p>
    <a href = "/shop/categories/chargers/{{ product.id }}" class = "btn btn-primary">View</a>
{% endblock %}

first/templates/first/charger.html
{% extends 'first/base.html' %}
    {% load static %}

    {% block nav-shop %}
        <li class = "nav-item active">
            <a class = "nav-link" href = "{% url 'first:category' %}">Shop</a>
        </li>
    {% endblock %}

    {% block content %}
        <div class = "container mt-xl-4">
            <div class = "row pb-xl-4">
                <div class = "col-xl-6">
                    <img src = "{{ charger.Image.url }}" width = "70%">
                </div>

                <div class = "col-lg-6">
                    <div class = "row">
                        <div class = "col-md-12">
                            <h1>{{ charger.Manufacturer }} {{ charger.Model_Name }}</h1>
                        </div>
                    </div>

                    <div class = "row pb-xl-4 border-bottom">
                        <div class = "col-md-12">
                            <span class = "badge badge-primary rounded-0 text-uppercase">Chargers</span>
                        </div>
                    </div>

                    <div class = "row pt-xl-4 border-bottom">
                        <div class = "col-md-12">
                            <div class = "description">
                                <p>{{ charger.Description }}</p>
                            </div>
                        </div>
                    </div>

                    <div class = "row pt-xl-4 pb-xl-4 border-bottom">
                        <div class = "col-md-4">
                            <h3 class = "text-success">&#x20B9; {{ charger.Price }}</h3>
                        </div>

                        <div class = "col-md-4">
                            <button type = "button" class = "btn btn-outline-primary">Add To Cart</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    	<div class = "container p-xl-3 text-center rounded" style = "background-color: #407DE1; color: white">
        	<span>Specifications</span>
        </div>

        <div class = "container mt-xl-4">
        	<table class = "table table-striped">
        		<tbody>
        			
        			<tr>
        				<th scope = "row">Manufacturer</th>
        				<td>{{ charger.Manufacturer }}</td>
        			</tr>

        			<tr>
        				<th scope = "row">Model Name</th>
        				<td>{{ charger.Model_Name }}</td>
        			</tr> 

        			<tr>
        				<th scope = "row">Model Number</th>
        				<td>{{ charger.Model_Number }}</td>
        			</tr>

        			<tr>
        				<th scope = "row">Power Input</th>
        				<td>{{ charger.Power_Input }}</td>
        			</tr>

        			<tr>
        				<th scope = "row">Power Output</th>
        				<td>{{ charger.Power_Output }} W</td>
        			</tr>

        			<tr>
        				<th scope = "row">Cable Length</th>
        				<td>{{ charger.Cable_Length }} m</td>
        			</tr>

        			<tr>
        				<th scope = "row">Cable Type</th>
        				<td>{{ charger.Cable_Type }}</td>
        			</tr>

        			<tr>
        				<th scope = "row">Warranty Type</th>
        				<td>{{ charger.Warranty_Type }}</td>
        			</tr>

        			<tr>
        				<th scope = "row">Warranty Duration</th>
        				<td>{{ charger.Warranty_Duration }}</td>
        			</tr>
        		</tbody>
        	</table>
        </div>
     {% endblock %}

first/templates/first/headset-card.html
{% extends 'first/product-card.html' %}

{% block price %}
	<p class = "card-text text-success">&#x20B9; {{ product.Price }}</p>
	<a href = "/shop/categories/headsets/{{ product.id }}" class = "btn btn-primary">View</a>
{% endblock %}

first/templates/first/laptop-card.html
{% extends 'first/product-card.html' %}

{% block price %}
    <p class = "card-text text-success">&#36; {{ product.Price }}</p>
    <a href = "/shop/categories/laptops/{{ product.id }}" class = "btn btn-primary">View</a>
{% endblock %}

first/templates/first/mobile-card.html
{% extends 'first/product-card.html' %}

{% block price %}
    <p class = "card-text text-success">&#x20B9; {{ product.Price }}</p>
    <a href = "{% url 'first:detail' product.id %}" class = "btn btn-primary">View</a>
{% endblock %}

first/templates/first/mobile.html
{% extends 'first/base.html' %}
    {% load static %}

    {% block nav-shop %}
        <li class = "nav-item active">
            <a class = "nav-link" href = "{% url 'first:category' %}">Shop</a>
        </li>
    {% endblock %}

    {% block content %}
        <div class = "container mt-xl-4">
            <div class = "row pb-xl-4">
                <div class = "col-xl-6">
                    <img src = "{{ mobile.Image.url }}">
                </div>

                <div class = "col-lg-6">
                    <div class = "row">
                        <div class = "col-md-12">
                            <h1>{{mobile.Manufacturer}} {{ mobile.Model_Name }}</h1>
                        </div>
                    </div>

                    <div class = "row pb-xl-4 border-bottom">
                        <div class = "col-md-12">
                            <span class = "badge badge-primary rounded-0 text-uppercase">Mobiles</span>
                        </div>
                    </div>

                    <div class = "row pt-xl-4 border-bottom">
                        <div class = "col-md-12">
                            <div class = "description">
                                <p>{{ mobile.Description }}</p>
                            </div>
                        </div>
                    </div>

                    <div class = "row pt-xl-4 pb-xl-4 border-bottom">
                        <div class = "col-md-4">
                            <h3 class = "text-success">&#x20B9; {{ mobile.Price }}</h3>
                        </div>

                        <div class = "col-md-4">
                            <form action = "{% url 'cart:cart_add' mobile.id %}" method = "post">
                                {{ cart_product_form }}
                                {% csrf_token %}
                                <input type = "submit" value = "Add to Cart" class = "btn btn-outline-primary {% if not request.user.is_authenticated %}disabled{% endif %}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class = "container p-xl-3 text-center rounded" style = "background-color: #407DE1; color: white">
            <span>Specifications</span>
        </div>

        <div class = "container mt-xl-4">
            <table class = "table table-striped">
                <tbody>
                    <tr>
                        <th scope = 'row'>Manufacturer</th>
                        <td>{{ mobile.Manufacturer }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Model Name</th>
                        <td>{{ mobile.Model_Name }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Model Number</th>
                        <td>{{ mobile.Model_Number }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Display Size</th>
                        <td>{{ mobile.Display_Size }} inches</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>CPU</th>
                        <td>{{ mobile.CPU }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>RAM</th>
                        <td>{{ mobile.RAM }} GB</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>GPU</th>
                        <td>{{ mobile.GPU }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Front Camera (Secondary)</th>
                        <td>{{ mobile.Front_Camera }} MP</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Rear Camera (Primary)</th>
                        <td>{{ mobile.Rear_Camera }} MP</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Weight</th>
                        <td>{{ mobile.Weight }} grams</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Resolution</th>
                        <td>{{ mobile.Resolution }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Battery Rating</th>
                        <td>{{ mobile.Battery_Rating }} mAh</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Colour</th>
                        <td>{{ mobile.Colour }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>OS</th>
                        <td>{{ mobile.OS }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Storage</th>
                        <td>{{ mobile.Storage }} GB</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Warranty Type</th>
                        <td>{{ mobile.Warranty_Type }}</td>
                    </tr>

                    <tr>
                        <th scope = 'row'>Warranty Duration</th>
                        <td>{{ mobile.Warranty_Duration }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <script type="text/javascript">      
            $(document).ready(function()      
            {     
                $('[data-toggle = "tooltip"]').tooltip();     
            });       
        </script>
    {% endblock %}

first/templates/first/other-card.html
{% extends 'first/product-card.html' %}

{% block price %}
    <p class = "card-text text-success">&#x20B9; {{ product.Price }}</p>
{% endblock %}

first/templates/first/product-card.html
{% extends 'first/base.html' %}

    {% block nav-shop %}
        <li class = "nav-item active">
            <a class = "nav-link" href = "{% url 'first:category' %}">Shop</a>
        </li>
    {% endblock %}

    {% block content %}
        {% for product in object_list %}
            <style>
                .card:hover{
                    box-shadow: 1px 8px 20px grey;
                    -webkit-transition:  box-shadow .3s ease-in;
                    transform: scale(1.1);
                }
            </style>
            <div class = "card mx-xl-4" style = "width: 18rem; display: inline-flex;">
                <img class = "card-img-top" src = "{{ product.Image.url }}" alt = "Card image cap" style = "max-height: 580px" >
                <div class = "card-body">
                    <h5 class = "card-title">{{ product.Manufacturer }} {{ product.Model_Name }}</h5>
                    {% block price %}
                    {% endblock %}
                </div>
            </div>
        {% endfor %}
    {% endblock %}

first/templates/first/tablet-card.html
{% extends 'first/product-card.html' %}

{% block price %}
	<p class = "card-text text-success">&#x20B9; {{ product.Price }}</p>
	<a href = "/shop/categories/tablets/{{ product.id }}" class = "btn btn-primary">View</a>
{% endblock %}